//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataExtractor.Cinemasight {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class CinemaSightExtractorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CinemaSightExtractorSettings defaultInstance = ((CinemaSightExtractorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CinemaSightExtractorSettings())));
        
        public static CinemaSightExtractorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.cinemasight.com/awards-history")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
            set {
                this["BaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(//div[@id=\'content\']/article/div[2]/table//tr//td//a)[position() > 1 and positio" +
            "n() < 92]")]
        public string XpathAwardIndexExtract {
            get {
                return ((string)(this["XpathAwardIndexExtract"]));
            }
            set {
                this["XpathAwardIndexExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cinemasight_awards.csv")]
        public string FileNameAwards {
            get {
                return ((string)(this["FileNameAwards"]));
            }
            set {
                this["FileNameAwards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cinemasight_ceremony.csv")]
        public string FileNameCeremonyDetails {
            get {
                return ((string)(this["FileNameCeremonyDetails"]));
            }
            set {
                this["FileNameCeremonyDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Year,Category,Winner,Key,Subkey")]
        public string ColumnNamesAwards {
            get {
                return ((string)(this["ColumnNamesAwards"]));
            }
            set {
                this["ColumnNamesAwards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Year,Topic,Winner,SubTopic,Value")]
        public string ColumnNamesCeremony {
            get {
                return ((string)(this["ColumnNamesCeremony"]));
            }
            set {
                this["ColumnNamesCeremony"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'content\']/article/div[2]/table[1]//tr/td[2]/p[position()<3]//a")]
        public string XpathYearSpecificIndices {
            get {
                return ((string)(this["XpathYearSpecificIndices"]));
            }
            set {
                this["XpathYearSpecificIndices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'content\']/article/div[2]/*[position() > 4]")]
        public string XpathAwardsYearSpecificCategoriesGroup {
            get {
                return ((string)(this["XpathAwardsYearSpecificCategoriesGroup"]));
            }
            set {
                this["XpathAwardsYearSpecificCategoriesGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'content\']/article/div[2]/*[position() > 1]")]
        public string XpathCeremoniesYearSpecific {
            get {
                return ((string)(this["XpathCeremoniesYearSpecific"]));
            }
            set {
                this["XpathCeremoniesYearSpecific"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProcessSpecificOscarYear {
            get {
                return ((string)(this["ProcessSpecificOscarYear"]));
            }
            set {
                this["ProcessSpecificOscarYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cinemasight_moments.csv")]
        public string FileNameMoments {
            get {
                return ((string)(this["FileNameMoments"]));
            }
            set {
                this["FileNameMoments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'content\']/article/div[2]//ol/li")]
        public string XpathAwardsNotes {
            get {
                return ((string)(this["XpathAwardsNotes"]));
            }
            set {
                this["XpathAwardsNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Year,Topic,SubTopic,Value")]
        public string ColumnNamesMoments {
            get {
                return ((string)(this["ColumnNamesMoments"]));
            }
            set {
                this["ColumnNamesMoments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipProcessing {
            get {
                return ((bool)(this["SkipProcessing"]));
            }
            set {
                this["SkipProcessing"] = value;
            }
        }
    }
}
